#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Asuto Sato ast1639st@gmail.com
# SPDX-License-Identifier: BSD-3-Clause
import sys

#num = sys.argv[1]
num = input()
judge = int(num) % 2

if judge == 0:
    print(str(num) + "は偶数")
else:
    print(str(num) + "は奇数")
